### ISSUE TITLE
Deepwind Jungle potions

### ISSUE THREAD

**Issue by TBG1000** [Warzone/Maps#249]
Speed potions on Deepwind Jungle (and potentially any other map that has potions) do not have the speed effect and appear as regular water bottles. This might be due to the 1.14 world conversion.

**Comment by Owehttamy** [comment]
Because I haven't played in newer versions, does this only happen in 1.8.9 from protocol support or is it just water bottles in the map now?

Also other maps like Turf Wars seem fine with their speed potions and splash potions, so it might just be Deepwind with the issues (let's hope)

**Comment by Owehttamy** [comment]
[region.zip](https://github.com/Warzone/Maps/files/3779488/region.zip)
Map already pruned but I'm too stupid to figure out how tf to replace the files

**Comment by Owehttamy** [comment]
#326
