### ISSUE TITLE
Relocate SunTest

### ISSUE THREAD

**Issue by Owehttamy** [Warzone/Maps#309]
SunTest is found in DTW when it's a DTM Map (Break gold blocks, not wool)

*Please merge my DTW pr first ty*

**Comment by BennyDoesTheStuff** [comment]
Please don't spam issues, please put them all in 1 issue.

**Comment by Owehttamy** [comment]
Reopen because it's not renaming

**Comment by jorgeberrex** [comment]
`Maps/DTW/SunTest` -> `Maps/DTM/SunTest`
