### ISSUE TITLE
Outdated Command blocks

### ISSUE THREAD

**Issue by BennyDoesTheStuff** [Warzone/Maps#345]
Ping Bomb is broken and doesn't work. It used to run on command blocks but they are outdated.

- Spawn points are incorrect.
- Old command blocks need to be removed
- Fireball generators need to be fixed.

**Comment by Owehttamy** [comment]
Are you stating it should be run off of something such as a function, or do the command blocks just need to be updated?

**Comment by BennyDoesTheStuff** [comment]
Well, most of the command blocks aren’t needed anymore as that functionality is possible in the JSON. Some of the command blocks are still needed, however (fireballs, world border when mid is blown up)

**Comment by BennyDoesTheStuff** [comment]
The command blocks that are still needed will need to be updated to be compatible. I would like to avoid using any command blocks, but spawning fireballs isn’t possible (I know the block generator is actually possible now in the JSON too)
