### ISSUE TITLE
Persisto & Race for Victory Pressure Plate Issue

### ISSUE THREAD

**Issue by residesJack** [Warzone/Maps#347]
On the maps Persisto and Race for Victory, players are instantly killed when stepping on pressure plates that lead to another island. 

**DEATH MESSAGE:** Player was killed by the environment. 

_Will grab screenshots / clips when these maps appear on the server._

**Comment by BennyDoesTheStuff** [comment]
That seems to be an issue with ProtocolSupport or the plugin itself

**Comment by Draem** [comment]
alas, the issue still remains

**Comment by BennyDoesTheStuff** [comment]
well this is the Maps repo, something like that should be posted in the main TGM repo as it’s not an issue with the maps themselve
