### ISSUE TITLE
Flint and steel can be used to burn almost entire maps and team grief

### ISSUE THREAD

**Issue by TBG1000** [Warzone/Maps#352]
Maps that have iron blocks or just iron in general along with gravel can be used to craft flint and steel. This can be used to entirely burn the map as most maps (if not all) have wooden structures at the spawn or elsewhere. It also affects player-created structures, considering that all invetory loadouts contain wood logs or wood planks to build bridges. Using flint and steel, players can team grief by burning these bridges, which slows down their team (and the opposite if the fire extends throughout the whole map).

The solution would be to disable crafting of flint and steel entirely, or setting the doFireTick gamerule to false.

**Comment by residesJack** [comment]
this can be seen on Fracture

**Comment by TBG1000** [comment]
Fixed a long time ago when Jorge disabled fire spread.
