### ISSUE TITLE
Unable to win game

### ISSUE THREAD

**Issue by BennyDoesStuff** [Warzone/Maps#361]
In Crossfire, people are unable to break the sponge, resulting in the runners not being able to win the game. I'm not too sure what we should do to fix it and make it possible for runners to win.

**Comment by scorpion808** [comment]
You break the sponge using the wooden sword that you get.

**Comment by BennyDoesTheStuff** [comment]
![Image](https://i.imgur.com/sum5Ixn.png)

**Comment by scorpion808** [comment]
Oh that's because you are too far away from the command blocks

**Comment by BennyDoesTheStuff** [comment]
ahhhh, we're going to need a better way to end the game then. I'll mess around with it this weekend but ideally, there should be a way to set a custom objective in the JSON rather than needing to use command blocks.

**Comment by scorpion808** [comment]
I mean you can just force load the chunks where the command blocks are at, but relying on JSON rather than relying on command blocks would be much better in the long term.

**Comment by BTKingly** [comment]
Would it be possible to add a monument to the map in order to fix this? Not sure how multiple gamemodes work on TGM.
