### ISSUE TITLE
Bayview itemremove issue

### ISSUE THREAD

**Issue by PundaChen** [Warzone/Maps#396]
There's a secret room in Bayview which requires items to be thrown into cauldrons, the itemremove stops this from happening and completely locks this room, this room is what most people used to hide in back when the itemremove wasn't a manual thing. 
Theres a few options here:
- Edit itemremove, allow one item to be thrown out but this ends up in the player dropping it on death
- Edit the map itself, change the cauldrons for a button or something
- Get rid of the room
- Just leave it as it is

I don't rlly know what's the best option

**Comment by BTKingly** [comment]
For a quick fix I could add an item to each teams kit, name it something like "Key Card"/"Throw Me In Cauldron". To prevent players from picking it up upon killing others, the item would go to itemkeep. The only two issues I can see are; 
- someone wouldn't know why they had that item
- infected would probably have more than 1, given the nature of itemkeep - so should players have more than 1 to begin?

**Comment by BTKingly** [comment]
I was just informed, and tested it myself - there are items hidden across the map in dispensers. None of the items are included in the itemremove, therefore there actually is no issue here.
