### ISSUE TITLE
Ricco: Fix spawn regions to avoid mass team killing

### ISSUE THREAD

**Issue by residal** [Warzone/Maps#412]
Players can destroy the blocks within the spawn of both teams, causing players to fall to their deaths. 

**Example:**

![image](https://user-images.githubusercontent.com/55336990/107340003-60f1af80-6b11-11eb-8375-cff03e16151e.png)

**Comment by BTKingly** [comment]
[This](https://github.com/Warzone/Maps/commit/9906797628e656fba7f127cc449b3ab0bbe99bed) should fix it
