### ISSUE TITLE
Hallows spawn region bug

### ISSUE THREAD

**Issue by Stay000** [Warzone/Maps#416]
https://imgur.com/aD1XKct
Spawn regions are messed up on the map Hallows, I'd also like to ask that where you place captured wool is made more clear. Spent a nice 15 seconds running around spawn looking where to place the wool.

**Comment by AtditC** [comment]
The wool podiums are only about 5 blocks away from the spawn point

**Comment by TBG1000** [comment]
Kinda late, but spawn regions were fixed #429
