### ISSUE TITLE
Dead Water map issues

### ISSUE THREAD

**Issue by CrazyisCreeps** [Warzone/Maps#782]
Cobwebs at spawn can be broken, I feel as though that shouldn't be intended, and the webs are designed to prevent newly spawned players from reaching the monument to defend as quickly.

Secondly water appears to flow across block 36? This may be more a TGM
 issue, it's interesting to see none the less. I suppose if boats are disabled this isn't really a huge issue. I guess TGM doesn't unload the block 36s? 
![2021-12-20_00 20 42](https://user-images.githubusercontent.com/7937351/146715865-717421ac-3d07-4c66-a70a-f16da71b7376.png)

**Comment by Owehttamy** [comment]
Cobwebs does seem like an accidental branch-off from the original map, however it's a very simple change to make.
The block 36 and water issue _is_ just TGM so nothing can be done there.

Unless someone else gets to fixing it, I'll return to my computer in about a week.

**Comment by BTKingly** [comment]
Fixed f85beb0
