### ISSUE TITLE
Issue with map Arctic V2

### ISSUE THREAD

**Issue by ghost** [Warzone/Maps#93]
So basically its a feature  in which I think shouldent be a thing. You can craft shears on ArcticV2 which gives an advantage as you can break the enemies wool in less than 5 seconds. I believe that if people start to find this out everyone will be triggered after they start and finish. It would get pretty annoying and there would be no way to defend at all. If you guys want to keep this, its fine. But in my opinion it wouldent be as fun. - Xounaut

P.S: You can only get iron on CTW maps except for Arctic V2 and another map that i do not know the name of :P

*This issue was submitted through our issue submission tool.*

**Comment by Owehttamy** [comment]
So how do we set up the disabling of crafting for shears for this map? I know the last pr was merged for the crafting module so is it something we change in the JSON or is it server-wide?

**Comment by ThatOneTqnk** [comment]
json

**Comment by Owehttamy** [comment]
json

**Comment by Owehttamy** [comment]
#316
